/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.solace.aaron.topic;

import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

import org.junit.Test;

import com.solace.aaron.topic.utils.TestDataGeneratorUtil;

import dev.solace.aaron.topic.TopicUtil;

/** Compares the results of topic matching of both regular and regex subs */
public class TestGeneratorTests {
	    
	
    @Test
    public void topicGeneratorTest() {
    	System.out.printf("%n################%nTopic Gen Tests%n");
    	for (int i=0; i<100; i++) {
    		System.out.println(TestDataGeneratorUtil.buildRandomTopic(20));
    	}
    }

    @Test
    public void subGeneratorTest() {
    	System.out.printf("%n################%nRandom Sub Gen Tests%n");
    	for (int i=0; i<100; i++) {
    		System.out.println(TestDataGeneratorUtil.buildRandomSub(20));
    	}
    }

    @Test
    public void buildValidSubsTest() {
    	System.out.printf("%n################%nValid Sub Tests%n");
    	Set<String> validSubs = new HashSet<>();
    	int num = 100_000;
    	for (int i=0; i<num; i++) {
    		String sub = TestDataGeneratorUtil.buildRandomSub(20);
    		if (TopicUtil.validateSub(sub)) {
    			validSubs.add(sub);
//    			System.out.println(sub);
    		}
    	}
    	System.out.printf("%,d subs -> %,d valid subs%n", num, validSubs.size());
    	System.out.println(validSubs.stream().limit(20).collect(Collectors.toSet()));
    }

}
